# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
waist_joint:
  ID: 0
  Return_Delay_Time: 250
  Moving_Speed: 150
  P_gain: 32
  I_gain: 20
  D_gain: 10

shoulder_shadow_joint:
  ID: 1
  Return_Delay_Time: 250
  Moving_Speed: 150
  P_gain: 32
  I_gain: 20
  D_gain: 10

shoulder_joint:
  ID: 2
  Return_Delay_Time: 250
  Moving_Speed: 150
  P_gain: 32
  I_gain: 20
  D_gain: 10

elbow_joint:
  ID: 3
  Return_Delay_Time: 250
  Moving_Speed: 150
  P_gain: 200
  I_gain: 0
  D_gain: 0

wrist_joint:
  ID: 4
  Return_Delay_Time: 250
  Moving_Speed: 150
  P_gain: 32
  I_gain: 20
  D_gain: 10

palm_joint:
  ID: 5
  Return_Delay_Time: 250
  Moving_Speed: 150

gripper_joint:
  ID: 6
  Return_Delay_Time: 250  
  Moving_Speed: 150
  Max_Torque: 300
