controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - waist_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
      - palm_joint
  - name: hand_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    parallel: false
    joints:
     - gripper_joint