controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - waist_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
      - palm_joint
  - name: hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    parallel: false
    joints:
      - finger1_joint
      - finger2_joint
      - gripper_joint